name: Editor

services:
  frontend:
    build: 
      context: ./sandbox
    container_name: Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./sandbox/src:/app/src
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  api:
    build:
      context: ./fastApi
    container_name: API
    ports:
      - "8000:8000"
    volumes:
      - ./fastApi:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]