# syntax=docker/dockerfile:1

FROM python:3.12.4
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs
    
WORKDIR /app
COPY ./ ./app

COPY requirements.txt ./

#Run the virtual environment
RUN python -m venv venv
RUN python -m pip install --no-cache-dir -r requirements.txt


# Copy the source code into the container.
COPY . .

# Expose the port that the application listens on.
EXPOSE 8000

# Run the application.
CMD uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
# CMD fastapi run main.py --host 127.0.0.1 --port 8000